# Generated by Django 4.2.30 on 2026-05-16 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=500, unique=True)),
                ('careers_url', models.URLField(blank=True, max_length=500)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('discovered_via', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('trust_score', models.IntegerField(default=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='SearchSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('language', models.CharField(default='en', help_text='Language of the query e.g. de, fr, en', max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('results_found', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-results_found'],
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('established', 'Established'), ('emerging', 'Emerging'), ('hypothesis', 'Hypothesis')], default='hypothesis', max_length=20)),
                ('confidence_score', models.IntegerField(default=50, help_text='0-100 confidence this is a real growing category')),
                ('job_count', models.IntegerField(default=0)),
                ('weekly_growth', models.FloatField(default=0.0, help_text='Week over week growth percentage')),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Taxonomy',
                'ordering': ['-job_count'],
            },
        ),
        migrations.CreateModel(
            name='JobStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_state', models.CharField(blank=True, max_length=20)),
                ('new_state', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Job state histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('apply_url', models.URLField(blank=True, max_length=500)),
                ('posting_language', models.CharField(default='en', help_text='Language the job post is written in e.g. de, fr, fi', max_length=10)),
                ('work_language', models.CharField(default='en', help_text='Language the actual work requires e.g. en, fr, es', max_length=100)),
                ('job_type', models.CharField(choices=[('transcription', 'Transcription'), ('annotation', 'Data Annotation'), ('ai_training', 'AI Training'), ('translation', 'Translation'), ('voice', 'Voice Recording'), ('content_moderation', 'Content Moderation'), ('qa', 'Quality Assurance'), ('emerging', 'Emerging Category'), ('other', 'Other')], default='other', max_length=50)),
                ('vacancy_state', models.CharField(choices=[('active', 'Active — real vacancy'), ('ghost_pipeline', 'Ghost pipeline — no real vacancy'), ('closed', 'Closed — not hiring'), ('no_page', 'No careers page yet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('geo_tier', models.IntegerField(choices=[(0, 'Unknown / not specified'), (1, 'Worldwide — no restriction'), (2, 'Africa / Kenya explicitly included'), (3, 'Legal/citizenship flag — remote work'), (4, 'Region restricted — investigate'), (5, 'Physical presence required — skip')], default=0)),
                ('onboarding_level', models.IntegerField(blank=True, choices=[(1, 'Level 1 — Test only, auto-onboard'), (2, 'Level 2 — Async form + review'), (3, 'Level 3 — Live video/phone interview'), (4, 'Level 4 — Document heavy')], null=True)),
                ('citizenship_flag', models.BooleanField(default=False)),
                ('citizenship_note', models.CharField(blank=True, max_length=500)),
                ('physical_required', models.BooleanField(default=False)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_confirmed', models.DateTimeField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company')),
            ],
            options={
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('success', 'Success'), ('blocked', 'Blocked'), ('error', 'Error'), ('captcha', 'CAPTCHA'), ('empty', 'Empty')], max_length=20)),
                ('http_code', models.IntegerField(blank=True, null=True)),
                ('protection_level', models.IntegerField(blank=True, help_text='1=none, 2=basic, 3=JS, 4=Cloudflare, 5=Enterprise', null=True)),
                ('jobs_found', models.IntegerField(default=0)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_logs', to='core.company')),
            ],
            options={
                'ordering': ['-crawled_at'],
            },
        ),
    ]
