# Generated by Django 4.2.30 on 2026-05-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('company_careers', 'Company Careers Page'), ('job_board', 'Job Board'), ('ats_page', 'ATS Platform Page'), ('social', 'Social / Community'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('posting_language', models.CharField(default='en', help_text='Language this source posts jobs in', max_length=10)),
                ('work_language', models.CharField(blank=True, help_text='Language the work requires if known', max_length=10)),
                ('discovered_via', models.CharField(blank=True, max_length=255)),
                ('discovered_query', models.TextField(blank=True, help_text='The search query that found this source')),
                ('is_active', models.BooleanField(default=True)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('crawl_frequency_hours', models.IntegerField(default=24, help_text='How often to re-crawl in hours')),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('protection_level', models.IntegerField(default=1, help_text='1=none, 2=basic, 3=JS, 4=Cloudflare')),
                ('jobs_found_total', models.IntegerField(default=0)),
                ('last_job_found', models.DateTimeField(blank=True, null=True)),
                ('trust_score', models.IntegerField(default=50)),
                ('first_discovered', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Discovered Source',
                'verbose_name_plural': 'Discovered Sources',
                'ordering': ['-jobs_found_total', '-first_discovered'],
            },
        ),
    ]
