# Generated by Django 4.2.30 on 2026-05-18 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_discoveredsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('saved', '📌 Saved'), ('applied', '✅ Applied'), ('interview', '🎯 Interview'), ('rejected', '❌ Rejected'), ('withdrawn', '↩️ Withdrawn')], default='saved', max_length=20)),
                ('email_used', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
