# Generated by Django 4.2.30 on 2026-05-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='platform_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('saved', '📌 Saved for Later'), ('applied', '✅ Applied'), ('pending_test', '📝 Test Pending'), ('test_passed', '🎯 Test Passed'), ('approved', '✅ Account Approved'), ('active_worker', '🟢 Active — Getting Work'), ('no_work', '⏳ Approved — No Work Yet'), ('follow_up', '📅 Follow Up Later'), ('waitlisted', '⏸️ Waitlisted'), ('interview', '🎙️ Interview Scheduled'), ('rejected', '❌ Rejected'), ('withdrawn', '↩️ Withdrawn')], default='saved', max_length=20),
        ),
    ]
