# Generated by Django 4.2.30 on 2026-05-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_dynamicquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_queued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
