# Generated by Django 4.2.30 on 2026-05-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_job_is_queued_job_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='careers_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='crawllog',
            name='url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
